language: python
matrix:
    include:
        - python: 3.6
          dist: bionic
        - python: 3.7
          dist: bionic
services:
    - docker
before_install:
    - test/travis_before_install.sh
install:
    - pip install -r backend/requirements.txt
    - pip install -r test/requirements.txt
    - pip install coverage coveralls
script:
    - test/travis_script.sh
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-client-10
