version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-database
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    depends_on:
      - db
    ports:
      - 4000:4000
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /code
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /code
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile-proxy
    ports:
      - 4040:80
    depends_on:
      - backend
      - frontend
